### ISSUE TITLE
TVS Diode footprint placement error?

### ISSUE THREAD

**Issue by aleibrecht** [ElectronicCats/Catwan_sensorwater#2]
Hi,

Could it be possible that TVS diode is using SOT footprint from a transistor Q# and that ground pin is misrouted?

Shouldn't the lone pad be connected to ground?

cheers

**Comment by wero1414** [comment]
We had a mistake with the footprint assignation we are debbuging other possible mistakes done on the design so i hope this week we're solving all those mistakes
